//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_InvokeDemo.WCFDemoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WCF_ServiceDemo.Models")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SId {
            get {
                return this.SIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SIdField, value) != true)) {
                    this.SIdField = value;
                    this.RaisePropertyChanged("SId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFDemoServiceReference.IDemoService")]
    public interface IDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/AddStudent", ReplyAction="http://tempuri.org/IDemoService/AddStudentResponse")]
        bool AddStudent(WCF_InvokeDemo.WCFDemoServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/AddStudent", ReplyAction="http://tempuri.org/IDemoService/AddStudentResponse")]
        System.Threading.Tasks.Task<bool> AddStudentAsync(WCF_InvokeDemo.WCFDemoServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/UpdateStudent", ReplyAction="http://tempuri.org/IDemoService/UpdateStudentResponse")]
        bool UpdateStudent(WCF_InvokeDemo.WCFDemoServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/UpdateStudent", ReplyAction="http://tempuri.org/IDemoService/UpdateStudentResponse")]
        System.Threading.Tasks.Task<bool> UpdateStudentAsync(WCF_InvokeDemo.WCFDemoServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/DeleteStudent", ReplyAction="http://tempuri.org/IDemoService/DeleteStudentResponse")]
        bool DeleteStudent(string sId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/DeleteStudent", ReplyAction="http://tempuri.org/IDemoService/DeleteStudentResponse")]
        System.Threading.Tasks.Task<bool> DeleteStudentAsync(string sId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetStudent", ReplyAction="http://tempuri.org/IDemoService/GetStudentResponse")]
        WCF_InvokeDemo.WCFDemoServiceReference.Student GetStudent(string sId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetStudent", ReplyAction="http://tempuri.org/IDemoService/GetStudentResponse")]
        System.Threading.Tasks.Task<WCF_InvokeDemo.WCFDemoServiceReference.Student> GetStudentAsync(string sId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetStudents", ReplyAction="http://tempuri.org/IDemoService/GetStudentsResponse")]
        WCF_InvokeDemo.WCFDemoServiceReference.Student[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetStudents", ReplyAction="http://tempuri.org/IDemoService/GetStudentsResponse")]
        System.Threading.Tasks.Task<WCF_InvokeDemo.WCFDemoServiceReference.Student[]> GetStudentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoServiceChannel : WCF_InvokeDemo.WCFDemoServiceReference.IDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoServiceClient : System.ServiceModel.ClientBase<WCF_InvokeDemo.WCFDemoServiceReference.IDemoService>, WCF_InvokeDemo.WCFDemoServiceReference.IDemoService {
        
        public DemoServiceClient() {
        }
        
        public DemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddStudent(WCF_InvokeDemo.WCFDemoServiceReference.Student student) {
            return base.Channel.AddStudent(student);
        }
        
        public System.Threading.Tasks.Task<bool> AddStudentAsync(WCF_InvokeDemo.WCFDemoServiceReference.Student student) {
            return base.Channel.AddStudentAsync(student);
        }
        
        public bool UpdateStudent(WCF_InvokeDemo.WCFDemoServiceReference.Student student) {
            return base.Channel.UpdateStudent(student);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStudentAsync(WCF_InvokeDemo.WCFDemoServiceReference.Student student) {
            return base.Channel.UpdateStudentAsync(student);
        }
        
        public bool DeleteStudent(string sId) {
            return base.Channel.DeleteStudent(sId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStudentAsync(string sId) {
            return base.Channel.DeleteStudentAsync(sId);
        }
        
        public WCF_InvokeDemo.WCFDemoServiceReference.Student GetStudent(string sId) {
            return base.Channel.GetStudent(sId);
        }
        
        public System.Threading.Tasks.Task<WCF_InvokeDemo.WCFDemoServiceReference.Student> GetStudentAsync(string sId) {
            return base.Channel.GetStudentAsync(sId);
        }
        
        public WCF_InvokeDemo.WCFDemoServiceReference.Student[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<WCF_InvokeDemo.WCFDemoServiceReference.Student[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
    }
}
